CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS routing_graph_versions(
    graph_version BIGINT PRIMARY KEY,
    status TEXT NOT NULL CHECK(status IN('building','ready','failed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    activated_at TIMESTAMPTZ NULL
);
CREATE TABLE IF NOT EXISTS osm_nodes(
    graph_version BIGINT NOT NULL,
    id BIGINT NOT NULL,
    geom geometry(Point,4326) NOT NULL,
    PRIMARY KEY(graph_version,id)
);
CREATE TABLE IF NOT EXISTS osm_ways(
    graph_version BIGINT NOT NULL,
    way_id BIGINT NOT NULL,
    highway TEXT,
    name TEXT,
    ref TEXT,
    oneway TEXT,
    access TEXT,
    vehicle TEXT,
    motor_vehicle TEXT,
    hgv TEXT,
    goods TEXT,
    hazmat TEXT,
    maxheight DOUBLE PRECISION,
    maxwidth DOUBLE PRECISION,
    maxlength DOUBLE PRECISION,
    maxweight DOUBLE PRECISION,
    maxaxleload DOUBLE PRECISION,
    maxspeed DOUBLE PRECISION,
    maxspeed_hgv DOUBLE PRECISION,
    tags JSONB,
    PRIMARY KEY(graph_version,way_id)
);
CREATE TABLE IF NOT EXISTS osm_way_nodes(
    graph_version BIGINT NOT NULL,
    way_id BIGINT NOT NULL,
    seq INT NOT NULL,
    node_id BIGINT NOT NULL,
    PRIMARY KEY(graph_version,way_id,seq)
);
CREATE TABLE IF NOT EXISTS road_edges(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    graph_version BIGINT NOT NULL,
    way_id BIGINT NOT NULL,
    source_node BIGINT NOT NULL,
    target_node BIGINT NOT NULL,
    direction SMALLINT NOT NULL,
    highway TEXT,
    name TEXT,
    ref TEXT,
    access TEXT,
    vehicle TEXT,
    motor_vehicle TEXT,
    hgv TEXT,
    goods TEXT,
    hazmat TEXT,
    maxheight DOUBLE PRECISION,
    maxwidth DOUBLE PRECISION,
    maxlength DOUBLE PRECISION,
    maxweight DOUBLE PRECISION,
    maxaxleload DOUBLE PRECISION,
    maxspeed DOUBLE PRECISION,
    maxspeed_hgv DOUBLE PRECISION,
    speed_kmh DOUBLE PRECISION NOT NULL DEFAULT 30,
    length_m DOUBLE PRECISION NOT NULL,
    routable BOOLEAN NOT NULL DEFAULT true,
    tags JSONB,
    country_code CHAR(2),
    is_connector BOOLEAN NOT NULL DEFAULT false,
    hierarchy_penalty REAL NOT NULL DEFAULT 0,
    geom geometry(LineString,4326) NOT NULL
);
ALTER TABLE road_edges ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE road_edges ADD COLUMN IF NOT EXISTS ref TEXT;
CREATE INDEX IF NOT EXISTS ix_road_edges_source ON road_edges(graph_version,source_node) WHERE routable;
CREATE INDEX IF NOT EXISTS ix_road_edges_target ON road_edges(graph_version,target_node) WHERE routable;
CREATE INDEX IF NOT EXISTS ix_road_edges_geom ON road_edges USING gist(geom);
CREATE TABLE IF NOT EXISTS turn_restrictions(
    graph_version BIGINT NOT NULL,
    osm_relation_id BIGINT NOT NULL,
    restriction TEXT,
    from_way_id BIGINT,
    to_way_id BIGINT,
    via_node_ids BIGINT[],
    via_way_ids BIGINT[],
    except_values TEXT,
    conditional TEXT,
    tags JSONB,
    PRIMARY KEY(graph_version,osm_relation_id)
);
CREATE TABLE IF NOT EXISTS compiled_turn_restrictions(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    graph_version BIGINT NOT NULL,
    osm_relation_id BIGINT NOT NULL,
    restriction TEXT NOT NULL,
    from_edge_id BIGINT NOT NULL,
    to_edge_id BIGINT NOT NULL,
    via_edge_ids BIGINT[] NOT NULL DEFAULT '{{}}',
    except_values TEXT,
    conditional TEXT,
    tags JSONB
);
CREATE INDEX IF NOT EXISTS ix_compiled_turn_from ON compiled_turn_restrictions(graph_version,from_edge_id);
CREATE TABLE IF NOT EXISTS routing_cells(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    graph_version BIGINT NOT NULL,
    level INT NOT NULL,
    parent_cell_id BIGINT,
    geom geometry(MultiPolygon,4326),
    edge_count INT NOT NULL DEFAULT 0,
    node_count INT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS routing_node_cells(
    graph_version BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    level INT NOT NULL,
    cell_id BIGINT NOT NULL,
    PRIMARY KEY(graph_version,node_id,level)
);
CREATE TABLE IF NOT EXISTS routing_edge_cells(
    graph_version BIGINT NOT NULL,
    edge_id BIGINT NOT NULL,
    partition_level INT NOT NULL,
    cell_id BIGINT NOT NULL,
    is_boundary_edge BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY(graph_version,edge_id,partition_level)
);
CREATE TABLE IF NOT EXISTS routing_boundaries(
    graph_version BIGINT NOT NULL,
    level INT NOT NULL,
    cell_a BIGINT NOT NULL,
    cell_b BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    edge_id BIGINT,
    PRIMARY KEY(graph_version,level,cell_a,cell_b,node_id)
);
CREATE TABLE IF NOT EXISTS routing_cell_adjacency(
    graph_version BIGINT NOT NULL,
    level INT NOT NULL,
    source_cell_id BIGINT NOT NULL,
    target_cell_id BIGINT NOT NULL,
    boundary_node_id BIGINT,
    edge_id BIGINT,
    PRIMARY KEY(graph_version,level,source_cell_id,target_cell_id,boundary_node_id)
);
CREATE TABLE IF NOT EXISTS routing_overlay_edges(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    graph_version BIGINT NOT NULL,
    partition_level INT NOT NULL,
    source_cell_id BIGINT NOT NULL,
    target_cell_id BIGINT NOT NULL,
    source_boundary_node BIGINT NOT NULL,
    target_boundary_node BIGINT NOT NULL,
    first_edge_id BIGINT,
    last_edge_id BIGINT,
    distance_m DOUBLE PRECISION,
    edge_count INT,
    child_path JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS country_routing_policy(
    country_code CHAR(2) NOT NULL,
    vehicle_class TEXT NOT NULL,
    highway TEXT NOT NULL,
    default_speed_kmh DOUBLE PRECISION,
    default_max_speed_kmh DOUBLE PRECISION,
    source TEXT,
    valid_from DATE,
    valid_to DATE,
    metadata JSONB,
    PRIMARY KEY(country_code,vehicle_class,highway)
);